"""
Worldwide Countries List
"""
COUNTRIES = [
    {"code": "WW", "name": "Worldwide", "regions": ["All"]},
    {"code": "SG", "name": "Singapore", "regions": ["Asia"]},
    {"code": "MY", "name": "Malaysia", "regions": ["Asia"]},
    {"code": "TH", "name": "Thailand", "regions": ["Asia"]},
    {"code": "ID", "name": "Indonesia", "regions": ["Asia"]},
    {"code": "PH", "name": "Philippines", "regions": ["Asia"]},
    {"code": "VN", "name": "Vietnam", "regions": ["Asia"]},
    {"code": "HK", "name": "Hong Kong", "regions": ["Asia"]},
    {"code": "JP", "name": "Japan", "regions": ["Asia"]},
    {"code": "KR", "name": "South Korea", "regions": ["Asia"]},
    {"code": "CN", "name": "China", "regions": ["Asia"]},
    {"code": "IN", "name": "India", "regions": ["Asia"]},
    {"code": "AU", "name": "Australia", "regions": ["Oceania"]},
    {"code": "NZ", "name": "New Zealand", "regions": ["Oceania"]},
    {"code": "US", "name": "United States", "regions": ["North America"]},
    {"code": "CA", "name": "Canada", "regions": ["North America"]},
    {"code": "GB", "name": "United Kingdom", "regions": ["Europe"]},
    {"code": "IE", "name": "Ireland", "regions": ["Europe"]},
    {"code": "DE", "name": "Germany", "regions": ["Europe"]},
    {"code": "FR", "name": "France", "regions": ["Europe"]},
    {"code": "NL", "name": "Netherlands", "regions": ["Europe"]},
    {"code": "BE", "name": "Belgium", "regions": ["Europe"]},
    {"code": "CH", "name": "Switzerland", "regions": ["Europe"]},
    {"code": "AT", "name": "Austria", "regions": ["Europe"]},
    {"code": "SE", "name": "Sweden", "regions": ["Europe"]},
    {"code": "NO", "name": "Norway", "regions": ["Europe"]},
    {"code": "DK", "name": "Denmark", "regions": ["Europe"]},
    {"code": "FI", "name": "Finland", "regions": ["Europe"]},
    {"code": "ES", "name": "Spain", "regions": ["Europe"]},
    {"code": "IT", "name": "Italy", "regions": ["Europe"]},
    {"code": "PT", "name": "Portugal", "regions": ["Europe"]},
    {"code": "PL", "name": "Poland", "regions": ["Europe"]},
    {"code": "CZ", "name": "Czech Republic", "regions": ["Europe"]},
    {"code": "AE", "name": "United Arab Emirates", "regions": ["Middle East"]},
    {"code": "SA", "name": "Saudi Arabia", "regions": ["Middle East"]},
    {"code": "IL", "name": "Israel", "regions": ["Middle East"]},
    {"code": "BR", "name": "Brazil", "regions": ["South America"]},
    {"code": "MX", "name": "Mexico", "regions": ["North America"]},
    {"code": "AR", "name": "Argentina", "regions": ["South America"]},
    {"code": "ZA", "name": "South Africa", "regions": ["Africa"]},
    {"code": "EG", "name": "Egypt", "regions": ["Africa"]},
    {"code": "NG", "name": "Nigeria", "regions": ["Africa"]},
    {"code": "KE", "name": "Kenya", "regions": ["Africa"]},
    {"code": "TW", "name": "Taiwan", "regions": ["Asia"]},
    {"code": "TR", "name": "Turkey", "regions": ["Europe", "Asia"]},
    {"code": "RU", "name": "Russia", "regions": ["Europe", "Asia"]},
    {"code": "GR", "name": "Greece", "regions": ["Europe"]},
    {"code": "RO", "name": "Romania", "regions": ["Europe"]},
    {"code": "HU", "name": "Hungary", "regions": ["Europe"]},
    {"code": "BG", "name": "Bulgaria", "regions": ["Europe"]},
    {"code": "HR", "name": "Croatia", "regions": ["Europe"]},
    {"code": "SK", "name": "Slovakia", "regions": ["Europe"]},
    {"code": "SI", "name": "Slovenia", "regions": ["Europe"]},
    {"code": "EE", "name": "Estonia", "regions": ["Europe"]},
    {"code": "LV", "name": "Latvia", "regions": ["Europe"]},
    {"code": "LT", "name": "Lithuania", "regions": ["Europe"]},
    {"code": "LU", "name": "Luxembourg", "regions": ["Europe"]},
    {"code": "IS", "name": "Iceland", "regions": ["Europe"]},
    {"code": "MT", "name": "Malta", "regions": ["Europe"]},
    {"code": "CY", "name": "Cyprus", "regions": ["Europe"]},
    {"code": "CL", "name": "Chile", "regions": ["South America"]},
    {"code": "CO", "name": "Colombia", "regions": ["South America"]},
    {"code": "PE", "name": "Peru", "regions": ["South America"]},
    {"code": "VE", "name": "Venezuela", "regions": ["South America"]},
    {"code": "EC", "name": "Ecuador", "regions": ["South America"]},
    {"code": "UY", "name": "Uruguay", "regions": ["South America"]},
    {"code": "PY", "name": "Paraguay", "regions": ["South America"]},
    {"code": "BO", "name": "Bolivia", "regions": ["South America"]},
    {"code": "CR", "name": "Costa Rica", "regions": ["North America"]},
    {"code": "PA", "name": "Panama", "regions": ["North America"]},
    {"code": "GT", "name": "Guatemala", "regions": ["North America"]},
    {"code": "DO", "name": "Dominican Republic", "regions": ["North America"]},
    {"code": "CU", "name": "Cuba", "regions": ["North America"]},
    {"code": "JM", "name": "Jamaica", "regions": ["North America"]},
    {"code": "BD", "name": "Bangladesh", "regions": ["Asia"]},
    {"code": "PK", "name": "Pakistan", "regions": ["Asia"]},
    {"code": "LK", "name": "Sri Lanka", "regions": ["Asia"]},
    {"code": "MM", "name": "Myanmar", "regions": ["Asia"]},
    {"code": "KH", "name": "Cambodia", "regions": ["Asia"]},
    {"code": "LA", "name": "Laos", "regions": ["Asia"]},
    {"code": "BN", "name": "Brunei", "regions": ["Asia"]},
    {"code": "MN", "name": "Mongolia", "regions": ["Asia"]},
    {"code": "NP", "name": "Nepal", "regions": ["Asia"]},
    {"code": "BT", "name": "Bhutan", "regions": ["Asia"]},
    {"code": "MV", "name": "Maldives", "regions": ["Asia"]},
    {"code": "AF", "name": "Afghanistan", "regions": ["Asia"]},
    {"code": "IQ", "name": "Iraq", "regions": ["Middle East"]},
    {"code": "IR", "name": "Iran", "regions": ["Middle East"]},
    {"code": "JO", "name": "Jordan", "regions": ["Middle East"]},
    {"code": "LB", "name": "Lebanon", "regions": ["Middle East"]},
    {"code": "KW", "name": "Kuwait", "regions": ["Middle East"]},
    {"code": "OM", "name": "Oman", "regions": ["Middle East"]},
    {"code": "QA", "name": "Qatar", "regions": ["Middle East"]},
    {"code": "BH", "name": "Bahrain", "regions": ["Middle East"]},
    {"code": "YE", "name": "Yemen", "regions": ["Middle East"]},
    {"code": "SY", "name": "Syria", "regions": ["Middle East"]},
    {"code": "PS", "name": "Palestine", "regions": ["Middle East"]},
    {"code": "MA", "name": "Morocco", "regions": ["Africa"]},
    {"code": "TN", "name": "Tunisia", "regions": ["Africa"]},
    {"code": "DZ", "name": "Algeria", "regions": ["Africa"]},
    {"code": "GH", "name": "Ghana", "regions": ["Africa"]},
    {"code": "ET", "name": "Ethiopia", "regions": ["Africa"]},
    {"code": "TZ", "name": "Tanzania", "regions": ["Africa"]},
    {"code": "UG", "name": "Uganda", "regions": ["Africa"]},
    {"code": "RW", "name": "Rwanda", "regions": ["Africa"]},
    {"code": "MW", "name": "Malawi", "regions": ["Africa"]},
    {"code": "ZM", "name": "Zambia", "regions": ["Africa"]},
    {"code": "ZW", "name": "Zimbabwe", "regions": ["Africa"]},
    {"code": "BW", "name": "Botswana", "regions": ["Africa"]},
    {"code": "NA", "name": "Namibia", "regions": ["Africa"]},
    {"code": "SN", "name": "Senegal", "regions": ["Africa"]},
    {"code": "CI", "name": "Ivory Coast", "regions": ["Africa"]},
    {"code": "CM", "name": "Cameroon", "regions": ["Africa"]},
    {"code": "AO", "name": "Angola", "regions": ["Africa"]},
    {"code": "MZ", "name": "Mozambique", "regions": ["Africa"]},
    {"code": "MG", "name": "Madagascar", "regions": ["Africa"]},
    {"code": "MU", "name": "Mauritius", "regions": ["Africa"]},
    {"code": "SC", "name": "Seychelles", "regions": ["Africa"]},
    {"code": "FJ", "name": "Fiji", "regions": ["Oceania"]},
    {"code": "PG", "name": "Papua New Guinea", "regions": ["Oceania"]},
    {"code": "NC", "name": "New Caledonia", "regions": ["Oceania"]},
    {"code": "PF", "name": "French Polynesia", "regions": ["Oceania"]},
    {"code": "WS", "name": "Samoa", "regions": ["Oceania"]},
    {"code": "TO", "name": "Tonga", "regions": ["Oceania"]},
    {"code": "VU", "name": "Vanuatu", "regions": ["Oceania"]},
    {"code": "SB", "name": "Solomon Islands", "regions": ["Oceania"]},
    {"code": "KI", "name": "Kiribati", "regions": ["Oceania"]},
    {"code": "TV", "name": "Tuvalu", "regions": ["Oceania"]},
    {"code": "NR", "name": "Nauru", "regions": ["Oceania"]},
    {"code": "PW", "name": "Palau", "regions": ["Oceania"]},
    {"code": "FM", "name": "Micronesia", "regions": ["Oceania"]},
    {"code": "MH", "name": "Marshall Islands", "regions": ["Oceania"]},
    {"code": "BY", "name": "Belarus", "regions": ["Europe"]},
    {"code": "UA", "name": "Ukraine", "regions": ["Europe"]},
    {"code": "MD", "name": "Moldova", "regions": ["Europe"]},
    {"code": "GE", "name": "Georgia", "regions": ["Europe", "Asia"]},
    {"code": "AM", "name": "Armenia", "regions": ["Europe", "Asia"]},
    {"code": "AZ", "name": "Azerbaijan", "regions": ["Europe", "Asia"]},
    {"code": "KZ", "name": "Kazakhstan", "regions": ["Europe", "Asia"]},
    {"code": "UZ", "name": "Uzbekistan", "regions": ["Asia"]},
    {"code": "TM", "name": "Turkmenistan", "regions": ["Asia"]},
    {"code": "TJ", "name": "Tajikistan", "regions": ["Asia"]},
    {"code": "KG", "name": "Kyrgyzstan", "regions": ["Asia"]},
    {"code": "AF", "name": "Afghanistan", "regions": ["Asia"]},
]

REGIONS = {
    "All": "All Regions",
    "Asia": "Asia",
    "Europe": "Europe",
    "North America": "North America",
    "South America": "South America",
    "Africa": "Africa",
    "Middle East": "Middle East",
    "Oceania": "Oceania"
}

def get_countries_by_region(region=None):
    """Get countries filtered by region"""
    if region and region != "All":
        return [c for c in COUNTRIES if region in c.get("regions", [])]
    return COUNTRIES

def get_country_by_code(code):
    """Get country by code"""
    for country in COUNTRIES:
        if country["code"] == code:
            return country
    return None
